---
- hosts: all
  gather_facts: yes
  become: yes
  vars_prompt:
  - name: "rhsm_username"
    prompt: "Enter RHN username"
    private: no
  - name: "rhsm_password"
    prompt: "Enter RHN password"
    private: yes
  - name: "ldap"
    prompt: "Do you want configuration with LDAP? (if so type 'yes')"
    private: no
  - name: "ldap_bindPassword"
    prompt: "Enter LDAP bind pass"
    private: yes
  tasks:
  - name: initialize subscription manager
    include_tasks: rhel.yml
    when: ansible_os_family == "RedHat"

  - name: disable security
    include_tasks: security.yml

  - include_role:
      name: geerlingguy.postgresql
    when: sonar == "db"

# we are not using "loop" over the roles to prevent ansible tower bug: https://bugzilla.redhat.com/show_bug.cgi?id=1600124 
  - include_role:
      name: geerlingguy.java
    when: sonar == "ui"

  - include_role:
      name: sonar
    when: sonar == "ui"

  - name: enable ldap configuration
    include: "ldap.yml"
    when: 
       -  ldap == "yes"
       -  sonar == "ui"
